spring.application.name=api-gateway
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

tqsport.services.auth=http://localhost:8081
tqsport.services.catalog=http://localhost:8082
tqsport.services.content=http://localhost:8083
tqsport.services.order=http://localhost:8084
tqsport.services.admin=http://localhost:8085
tqsport.services.cart=http://localhost:8086

tqsport.jwt.secret=tqsport-local-dev-secret-change-me

management.endpoints.web.exposure.include=health,info
debug=false
logging.level.root=INFO
logging.level.org.springframework=INFO
