quarkus.http.port=8080
quarkus.http.root-path=/
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/tqsport?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=UTC
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.flyway.migrate-at-start=false
quarkus.flyway.enabled=false

mp.openapi.extensions.smallrye.info.title=TQSport API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=REST API for football apparel commerce, admin workflows, UTF-8 Vietnamese content, and JWT RBAC.

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=tqsport
smallrye.jwt.sign.key.location=privateKey.pem
